apiVersion: apps/v1
kind: Deployment
metadata:
  name: sycamore-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sycamore-home
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sycamore-home
    spec:
      containers:
      - image: gcr.io/single-planet-281907/sycamore-home:latest
        name: sycamore-home
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        envFrom:
          - secretRef:
              name: home-secret

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sycamore-home
  name: sycamore-home
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: sycamore-home
